// Code generated by go-swagger; DO NOT EDIT.

package plugin

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewEnablePluginParams creates a new EnablePluginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEnablePluginParams() *EnablePluginParams {
	return NewEnablePluginParamsWithTimeout(cr.DefaultTimeout)
}

// NewEnablePluginParamsWithTimeout creates a new EnablePluginParams object
// with the ability to set a timeout on a request.
func NewEnablePluginParamsWithTimeout(timeout time.Duration) *EnablePluginParams {
	return &EnablePluginParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewEnablePluginParamsWithContext creates a new EnablePluginParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [EnablePluginParams].
func NewEnablePluginParamsWithContext(ctx context.Context) *EnablePluginParams {
	return &EnablePluginParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewEnablePluginParamsWithHTTPClient creates a new EnablePluginParams object
// with the ability to set a custom HTTPClient for a request.
func NewEnablePluginParamsWithHTTPClient(client *http.Client) *EnablePluginParams {
	return &EnablePluginParams{
		HTTPClient: client,
	}
}

/*
EnablePluginParams contains all the parameters to send to the API endpoint

	for the enable plugin operation.

	Typically these are written to a http.Request.
*/
type EnablePluginParams struct {

	// ID.
	//
	// the plugin id
	//
	// Format: int64
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the enable plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnablePluginParams) WithDefaults() *EnablePluginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the enable plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EnablePluginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the enable plugin params.
func (o *EnablePluginParams) WithTimeout(timeout time.Duration) *EnablePluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the enable plugin params.
func (o *EnablePluginParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the enable plugin params.
//
// Deprecated: use the operation call with context to pass the context instead of [EnablePluginParams].
func (o *EnablePluginParams) WithContext(ctx context.Context) *EnablePluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the enable plugin params.
//
// Deprecated: use the operation call with context to pass the context instead of [EnablePluginParams].
func (o *EnablePluginParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the enable plugin params.
func (o *EnablePluginParams) WithHTTPClient(client *http.Client) *EnablePluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the enable plugin params.
func (o *EnablePluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the enable plugin params.
func (o *EnablePluginParams) WithID(id int64) *EnablePluginParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the enable plugin params.
func (o *EnablePluginParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *EnablePluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
