// Code generated by go-swagger; DO NOT EDIT.

package plugin

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new plugin API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new plugin API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new plugin API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for plugin API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithContentType allows the client to force the Content-Type header
// to negotiate a specific Consumer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithContentType(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ConsumesMediaTypes = []string{mime}
	}
}

// WithContentTypeApplicationJSON sets the Content-Type header to "application/json".
func WithContentTypeApplicationJSON(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/json"}
}

// WithContentTypeApplicationxYaml sets the Content-Type header to "application/x-yaml".
func WithContentTypeApplicationxYaml(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/x-yaml"}
}

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptApplicationxYaml sets the Accept header to "application/x-yaml".
func WithAcceptApplicationxYaml(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/x-yaml"}
}

// ClientService is the interface for Client methods.
type ClientService interface {

	// DisablePlugin disable a plugin.
	DisablePlugin(params *DisablePluginParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DisablePluginOK, error)

	// DisablePluginContext disable a plugin.
	DisablePluginContext(ctx context.Context, params *DisablePluginParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DisablePluginOK, error)

	// EnablePlugin enable a plugin.
	EnablePlugin(params *EnablePluginParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*EnablePluginOK, error)

	// EnablePluginContext enable a plugin.
	EnablePluginContext(ctx context.Context, params *EnablePluginParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*EnablePluginOK, error)

	// GetPluginConfig get y a m l configuration for configurer plugin.
	GetPluginConfig(params *GetPluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginConfigOK, error)

	// GetPluginConfigContext get y a m l configuration for configurer plugin.
	GetPluginConfigContext(ctx context.Context, params *GetPluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginConfigOK, error)

	// GetPluginDisplay get display info for a displayer plugin.
	GetPluginDisplay(params *GetPluginDisplayParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginDisplayOK, error)

	// GetPluginDisplayContext get display info for a displayer plugin.
	GetPluginDisplayContext(ctx context.Context, params *GetPluginDisplayParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginDisplayOK, error)

	// GetPlugins return all plugins.
	GetPlugins(params *GetPluginsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginsOK, error)

	// GetPluginsContext return all plugins.
	GetPluginsContext(ctx context.Context, params *GetPluginsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginsOK, error)

	// UpdatePluginConfig update y a m l configuration for configurer plugin.
	UpdatePluginConfig(params *UpdatePluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdatePluginConfigOK, error)

	// UpdatePluginConfigContext update y a m l configuration for configurer plugin.
	UpdatePluginConfigContext(ctx context.Context, params *UpdatePluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdatePluginConfigOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// DisablePlugin disables a plugin.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DisablePluginContext] instead.
func (a *Client) DisablePlugin(params *DisablePluginParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DisablePluginOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DisablePluginContext(ctx, params, authInfo, opts...)
}

// DisablePluginContext disables a plugin.
//
// Do not use the deprecated [DisablePluginParams.Context] with this method: it would be ignored.
func (a *Client) DisablePluginContext(ctx context.Context, params *DisablePluginParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DisablePluginOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDisablePluginParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "disablePlugin",
		Method:             "POST",
		PathPattern:        "/plugin/{id}/disable",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DisablePluginReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DisablePluginOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for disablePlugin: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// EnablePlugin enables a plugin.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.EnablePluginContext] instead.
func (a *Client) EnablePlugin(params *EnablePluginParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*EnablePluginOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.EnablePluginContext(ctx, params, authInfo, opts...)
}

// EnablePluginContext enables a plugin.
//
// Do not use the deprecated [EnablePluginParams.Context] with this method: it would be ignored.
func (a *Client) EnablePluginContext(ctx context.Context, params *EnablePluginParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*EnablePluginOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewEnablePluginParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "enablePlugin",
		Method:             "POST",
		PathPattern:        "/plugin/{id}/enable",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &EnablePluginReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*EnablePluginOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for enablePlugin: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetPluginConfig gets y a m l configuration for configurer plugin.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetPluginConfigContext] instead.
func (a *Client) GetPluginConfig(params *GetPluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetPluginConfigContext(ctx, params, authInfo, opts...)
}

// GetPluginConfigContext gets y a m l configuration for configurer plugin.
//
// Do not use the deprecated [GetPluginConfigParams.Context] with this method: it would be ignored.
func (a *Client) GetPluginConfigContext(ctx context.Context, params *GetPluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetPluginConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getPluginConfig",
		Method:             "GET",
		PathPattern:        "/plugin/{id}/config",
		ProducesMediaTypes: []string{"application/x-yaml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetPluginConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetPluginConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getPluginConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetPluginDisplay gets display info for a displayer plugin.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetPluginDisplayContext] instead.
func (a *Client) GetPluginDisplay(params *GetPluginDisplayParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginDisplayOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetPluginDisplayContext(ctx, params, authInfo, opts...)
}

// GetPluginDisplayContext gets display info for a displayer plugin.
//
// Do not use the deprecated [GetPluginDisplayParams.Context] with this method: it would be ignored.
func (a *Client) GetPluginDisplayContext(ctx context.Context, params *GetPluginDisplayParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginDisplayOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetPluginDisplayParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getPluginDisplay",
		Method:             "GET",
		PathPattern:        "/plugin/{id}/display",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetPluginDisplayReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetPluginDisplayOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getPluginDisplay: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetPlugins returns all plugins.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetPluginsContext] instead.
func (a *Client) GetPlugins(params *GetPluginsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetPluginsContext(ctx, params, authInfo, opts...)
}

// GetPluginsContext returns all plugins.
//
// Do not use the deprecated [GetPluginsParams.Context] with this method: it would be ignored.
func (a *Client) GetPluginsContext(ctx context.Context, params *GetPluginsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetPluginsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetPluginsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getPlugins",
		Method:             "GET",
		PathPattern:        "/plugin",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetPluginsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetPluginsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getPlugins: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// UpdatePluginConfig updates y a m l configuration for configurer plugin.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.UpdatePluginConfigContext] instead.
func (a *Client) UpdatePluginConfig(params *UpdatePluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdatePluginConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.UpdatePluginConfigContext(ctx, params, authInfo, opts...)
}

// UpdatePluginConfigContext updates y a m l configuration for configurer plugin.
//
// Do not use the deprecated [UpdatePluginConfigParams.Context] with this method: it would be ignored.
func (a *Client) UpdatePluginConfigContext(ctx context.Context, params *UpdatePluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdatePluginConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewUpdatePluginConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "updatePluginConfig",
		Method:             "POST",
		PathPattern:        "/plugin/{id}/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/x-yaml"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdatePluginConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*UpdatePluginConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updatePluginConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [PluginParams].
	ctx context.Context
}
