// Code generated by go-swagger; DO NOT EDIT.

package plugin

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewUpdatePluginConfigParams creates a new UpdatePluginConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePluginConfigParams() *UpdatePluginConfigParams {
	return NewUpdatePluginConfigParamsWithTimeout(cr.DefaultTimeout)
}

// NewUpdatePluginConfigParamsWithTimeout creates a new UpdatePluginConfigParams object
// with the ability to set a timeout on a request.
func NewUpdatePluginConfigParamsWithTimeout(timeout time.Duration) *UpdatePluginConfigParams {
	return &UpdatePluginConfigParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewUpdatePluginConfigParamsWithContext creates a new UpdatePluginConfigParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdatePluginConfigParams].
func NewUpdatePluginConfigParamsWithContext(ctx context.Context) *UpdatePluginConfigParams {
	return &UpdatePluginConfigParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewUpdatePluginConfigParamsWithHTTPClient creates a new UpdatePluginConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePluginConfigParamsWithHTTPClient(client *http.Client) *UpdatePluginConfigParams {
	return &UpdatePluginConfigParams{
		HTTPClient: client,
	}
}

/*
UpdatePluginConfigParams contains all the parameters to send to the API endpoint

	for the update plugin config operation.

	Typically these are written to a http.Request.
*/
type UpdatePluginConfigParams struct {

	// ID.
	//
	// the plugin id
	//
	// Format: int64
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the update plugin config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePluginConfigParams) WithDefaults() *UpdatePluginConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update plugin config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePluginConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update plugin config params.
func (o *UpdatePluginConfigParams) WithTimeout(timeout time.Duration) *UpdatePluginConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update plugin config params.
func (o *UpdatePluginConfigParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the update plugin config params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdatePluginConfigParams].
func (o *UpdatePluginConfigParams) WithContext(ctx context.Context) *UpdatePluginConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update plugin config params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdatePluginConfigParams].
func (o *UpdatePluginConfigParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the update plugin config params.
func (o *UpdatePluginConfigParams) WithHTTPClient(client *http.Client) *UpdatePluginConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update plugin config params.
func (o *UpdatePluginConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update plugin config params.
func (o *UpdatePluginConfigParams) WithID(id int64) *UpdatePluginConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update plugin config params.
func (o *UpdatePluginConfigParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *UpdatePluginConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
