name: Test Nix

on:
  pull_request: {}
  push:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        host: [melon]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Build system configuration
        run: /run/current-system/sw/bin/nix-shell -p nh --run "nh os build ."