name: Test Nix

on:
  pull_request: {}
  push:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        host: [melon]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Build system configuration
        run: |
          nixos-rebuild build --flake .
          NEW="$(readlink -f /nix/var/nix/profiles/system)"
          OLD="$(readlink -f /run/current-system)"
          nix-shell -p dix --run "dix $OLD $NEW"
        env:
          PATH: /run/current-system/sw/bin:$PATH
          NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos