name: Test Nix

on:
  pull_request: {}
  push:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        host: [melon]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Build system configuration
        run: nh os build .