name: Update Nix

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch: {}
  push:
    branches:
      - update-workflow

jobs:
  update:
    runs-on: debian
    steps:
      - uses: actions/checkout@v5
      - uses: https://github.com/DeterminateSystems/nix-installer-action@v22
      - name: Run nix flake update
        run: nix flake update
      - name: Create/Update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'flake: update inputs'
          title: 'flake: update inputs'
          branch: update/flake-inputs
          base: master
          delete-branch: true
          token: ${{ secrets.UPDATE_TOKEN }}
