name: Update Nix

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch: {}
  pull_request: {}

jobs:
  update:
    runs-on: debian
    steps:
      - uses: actions/checkout@v5

      - uses: https://github.com/cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-26.05

      - name: Run nix flake update
        run: nix flake update
        env:
          PATH: /run/current-system/sw/bin:$PATH

      - name: Create/Update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'flake: update inputs'
          title: 'flake: update inputs'
          branch: update/flake-inputs
          base: master
          delete-branch: true
