// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"context"
	"net/http"
	"time"

	"github.com/daniel-w-innes/nixos-konnected-exporter/gotify/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateCurrentUserParams creates a new UpdateCurrentUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateCurrentUserParams() *UpdateCurrentUserParams {
	return NewUpdateCurrentUserParamsWithTimeout(cr.DefaultTimeout)
}

// NewUpdateCurrentUserParamsWithTimeout creates a new UpdateCurrentUserParams object
// with the ability to set a timeout on a request.
func NewUpdateCurrentUserParamsWithTimeout(timeout time.Duration) *UpdateCurrentUserParams {
	return &UpdateCurrentUserParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewUpdateCurrentUserParamsWithContext creates a new UpdateCurrentUserParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateCurrentUserParams].
func NewUpdateCurrentUserParamsWithContext(ctx context.Context) *UpdateCurrentUserParams {
	return &UpdateCurrentUserParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewUpdateCurrentUserParamsWithHTTPClient creates a new UpdateCurrentUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateCurrentUserParamsWithHTTPClient(client *http.Client) *UpdateCurrentUserParams {
	return &UpdateCurrentUserParams{
		HTTPClient: client,
	}
}

/*
UpdateCurrentUserParams contains all the parameters to send to the API endpoint

	for the update current user operation.

	Typically these are written to a http.Request.
*/
type UpdateCurrentUserParams struct {

	// Body.
	//
	// the user
	Body *models.UserExternalPass

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the update current user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCurrentUserParams) WithDefaults() *UpdateCurrentUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update current user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCurrentUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update current user params.
func (o *UpdateCurrentUserParams) WithTimeout(timeout time.Duration) *UpdateCurrentUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update current user params.
func (o *UpdateCurrentUserParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the update current user params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateCurrentUserParams].
func (o *UpdateCurrentUserParams) WithContext(ctx context.Context) *UpdateCurrentUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update current user params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateCurrentUserParams].
func (o *UpdateCurrentUserParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the update current user params.
func (o *UpdateCurrentUserParams) WithHTTPClient(client *http.Client) *UpdateCurrentUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update current user params.
func (o *UpdateCurrentUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update current user params.
func (o *UpdateCurrentUserParams) WithBody(body *models.UserExternalPass) *UpdateCurrentUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update current user params.
func (o *UpdateCurrentUserParams) SetBody(body *models.UserExternalPass) {
	o.Body = body
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *UpdateCurrentUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
