// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"context"
	"net/http"
	"time"

	"github.com/daniel-w-innes/nixos-konnected-exporter/gotify/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewUpdateUserParams creates a new UpdateUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateUserParams() *UpdateUserParams {
	return NewUpdateUserParamsWithTimeout(cr.DefaultTimeout)
}

// NewUpdateUserParamsWithTimeout creates a new UpdateUserParams object
// with the ability to set a timeout on a request.
func NewUpdateUserParamsWithTimeout(timeout time.Duration) *UpdateUserParams {
	return &UpdateUserParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewUpdateUserParamsWithContext creates a new UpdateUserParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateUserParams].
func NewUpdateUserParamsWithContext(ctx context.Context) *UpdateUserParams {
	return &UpdateUserParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewUpdateUserParamsWithHTTPClient creates a new UpdateUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateUserParamsWithHTTPClient(client *http.Client) *UpdateUserParams {
	return &UpdateUserParams{
		HTTPClient: client,
	}
}

/*
UpdateUserParams contains all the parameters to send to the API endpoint

	for the update user operation.

	Typically these are written to a http.Request.
*/
type UpdateUserParams struct {

	// Body.
	//
	// the updated user
	Body *models.UpdateUserExternal

	// ID.
	//
	// the user id
	//
	// Format: int64
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the update user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserParams) WithDefaults() *UpdateUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update user params.
func (o *UpdateUserParams) WithTimeout(timeout time.Duration) *UpdateUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update user params.
func (o *UpdateUserParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the update user params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateUserParams].
func (o *UpdateUserParams) WithContext(ctx context.Context) *UpdateUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update user params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateUserParams].
func (o *UpdateUserParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the update user params.
func (o *UpdateUserParams) WithHTTPClient(client *http.Client) *UpdateUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update user params.
func (o *UpdateUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update user params.
func (o *UpdateUserParams) WithBody(body *models.UpdateUserExternal) *UpdateUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update user params.
func (o *UpdateUserParams) SetBody(body *models.UpdateUserExternal) {
	o.Body = body
}

// WithID adds the id to the update user params.
func (o *UpdateUserParams) WithID(id int64) *UpdateUserParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update user params.
func (o *UpdateUserParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *UpdateUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
