// Code generated by go-swagger; DO NOT EDIT.

package application

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new application API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new application API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new application API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for application API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithContentType allows the client to force the Content-Type header
// to negotiate a specific Consumer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithContentType(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ConsumesMediaTypes = []string{mime}
	}
}

// WithContentTypeApplicationJSON sets the Content-Type header to "application/json".
func WithContentTypeApplicationJSON(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/json"}
}

// WithContentTypeMultipartFormData sets the Content-Type header to "multipart/form-data".
func WithContentTypeMultipartFormData(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"multipart/form-data"}
}

// ClientService is the interface for Client methods.
type ClientService interface {

	// CreateApp create an application.
	CreateApp(params *CreateAppParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateAppOK, error)

	// CreateAppContext create an application.
	CreateAppContext(ctx context.Context, params *CreateAppParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateAppOK, error)

	// DeleteApp delete an application.
	DeleteApp(params *DeleteAppParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAppOK, error)

	// DeleteAppContext delete an application.
	DeleteAppContext(ctx context.Context, params *DeleteAppParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAppOK, error)

	// GetApps return all applications.
	GetApps(params *GetAppsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAppsOK, error)

	// GetAppsContext return all applications.
	GetAppsContext(ctx context.Context, params *GetAppsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAppsOK, error)

	// RemoveAppImage deletes an image of an application.
	RemoveAppImage(params *RemoveAppImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveAppImageOK, error)

	// RemoveAppImageContext deletes an image of an application.
	RemoveAppImageContext(ctx context.Context, params *RemoveAppImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveAppImageOK, error)

	// UpdateApplication update an application.
	UpdateApplication(params *UpdateApplicationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateApplicationOK, error)

	// UpdateApplicationContext update an application.
	UpdateApplicationContext(ctx context.Context, params *UpdateApplicationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateApplicationOK, error)

	// UploadAppImage upload an image for an application.
	UploadAppImage(params *UploadAppImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UploadAppImageOK, error)

	// UploadAppImageContext upload an image for an application.
	UploadAppImageContext(ctx context.Context, params *UploadAppImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UploadAppImageOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// CreateApp creates an application.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.CreateAppContext] instead.
func (a *Client) CreateApp(params *CreateAppParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateAppOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.CreateAppContext(ctx, params, authInfo, opts...)
}

// CreateAppContext creates an application.
//
// Do not use the deprecated [CreateAppParams.Context] with this method: it would be ignored.
func (a *Client) CreateAppContext(ctx context.Context, params *CreateAppParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateAppOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCreateAppParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "createApp",
		Method:             "POST",
		PathPattern:        "/application",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateAppReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CreateAppOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createApp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// DeleteApp deletes an application.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteAppContext] instead.
func (a *Client) DeleteApp(params *DeleteAppParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAppOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteAppContext(ctx, params, authInfo, opts...)
}

// DeleteAppContext deletes an application.
//
// Do not use the deprecated [DeleteAppParams.Context] with this method: it would be ignored.
func (a *Client) DeleteAppContext(ctx context.Context, params *DeleteAppParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAppOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAppParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteApp",
		Method:             "DELETE",
		PathPattern:        "/application/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteAppReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAppOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteApp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetApps returns all applications.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetAppsContext] instead.
func (a *Client) GetApps(params *GetAppsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAppsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetAppsContext(ctx, params, authInfo, opts...)
}

// GetAppsContext returns all applications.
//
// Do not use the deprecated [GetAppsParams.Context] with this method: it would be ignored.
func (a *Client) GetAppsContext(ctx context.Context, params *GetAppsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAppsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAppsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getApps",
		Method:             "GET",
		PathPattern:        "/application",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAppsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAppsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getApps: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// RemoveAppImage deletes an image of an application.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.RemoveAppImageContext] instead.
func (a *Client) RemoveAppImage(params *RemoveAppImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveAppImageOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.RemoveAppImageContext(ctx, params, authInfo, opts...)
}

// RemoveAppImageContext deletes an image of an application.
//
// Do not use the deprecated [RemoveAppImageParams.Context] with this method: it would be ignored.
func (a *Client) RemoveAppImageContext(ctx context.Context, params *RemoveAppImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveAppImageOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRemoveAppImageParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "removeAppImage",
		Method:             "DELETE",
		PathPattern:        "/application/{id}/image",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RemoveAppImageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RemoveAppImageOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for removeAppImage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// UpdateApplication updates an application.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.UpdateApplicationContext] instead.
func (a *Client) UpdateApplication(params *UpdateApplicationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateApplicationOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.UpdateApplicationContext(ctx, params, authInfo, opts...)
}

// UpdateApplicationContext updates an application.
//
// Do not use the deprecated [UpdateApplicationParams.Context] with this method: it would be ignored.
func (a *Client) UpdateApplicationContext(ctx context.Context, params *UpdateApplicationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateApplicationOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewUpdateApplicationParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "updateApplication",
		Method:             "PUT",
		PathPattern:        "/application/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdateApplicationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*UpdateApplicationOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateApplication: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// UploadAppImage uploads an image for an application.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.UploadAppImageContext] instead.
func (a *Client) UploadAppImage(params *UploadAppImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UploadAppImageOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.UploadAppImageContext(ctx, params, authInfo, opts...)
}

// UploadAppImageContext uploads an image for an application.
//
// Do not use the deprecated [UploadAppImageParams.Context] with this method: it would be ignored.
func (a *Client) UploadAppImageContext(ctx context.Context, params *UploadAppImageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UploadAppImageOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewUploadAppImageParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "uploadAppImage",
		Method:             "POST",
		PathPattern:        "/application/{id}/image",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UploadAppImageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*UploadAppImageOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for uploadAppImage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [ApplicationParams].
	ctx context.Context
}
