// Code generated by go-swagger; DO NOT EDIT.

package application

import (
	"context"
	"net/http"
	"time"

	"github.com/daniel-w-innes/nixos-konnected-exporter/gotify/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewUpdateApplicationParams creates a new UpdateApplicationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateApplicationParams() *UpdateApplicationParams {
	return NewUpdateApplicationParamsWithTimeout(cr.DefaultTimeout)
}

// NewUpdateApplicationParamsWithTimeout creates a new UpdateApplicationParams object
// with the ability to set a timeout on a request.
func NewUpdateApplicationParamsWithTimeout(timeout time.Duration) *UpdateApplicationParams {
	return &UpdateApplicationParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewUpdateApplicationParamsWithContext creates a new UpdateApplicationParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateApplicationParams].
func NewUpdateApplicationParamsWithContext(ctx context.Context) *UpdateApplicationParams {
	return &UpdateApplicationParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewUpdateApplicationParamsWithHTTPClient creates a new UpdateApplicationParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateApplicationParamsWithHTTPClient(client *http.Client) *UpdateApplicationParams {
	return &UpdateApplicationParams{
		HTTPClient: client,
	}
}

/*
UpdateApplicationParams contains all the parameters to send to the API endpoint

	for the update application operation.

	Typically these are written to a http.Request.
*/
type UpdateApplicationParams struct {

	// Body.
	//
	// the application to update
	Body *models.ApplicationParams

	// ID.
	//
	// the application id
	//
	// Format: int64
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the update application params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateApplicationParams) WithDefaults() *UpdateApplicationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update application params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateApplicationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update application params.
func (o *UpdateApplicationParams) WithTimeout(timeout time.Duration) *UpdateApplicationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update application params.
func (o *UpdateApplicationParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the update application params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateApplicationParams].
func (o *UpdateApplicationParams) WithContext(ctx context.Context) *UpdateApplicationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update application params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateApplicationParams].
func (o *UpdateApplicationParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the update application params.
func (o *UpdateApplicationParams) WithHTTPClient(client *http.Client) *UpdateApplicationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update application params.
func (o *UpdateApplicationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update application params.
func (o *UpdateApplicationParams) WithBody(body *models.ApplicationParams) *UpdateApplicationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update application params.
func (o *UpdateApplicationParams) SetBody(body *models.ApplicationParams) {
	o.Body = body
}

// WithID adds the id to the update application params.
func (o *UpdateApplicationParams) WithID(id int64) *UpdateApplicationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update application params.
func (o *UpdateApplicationParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *UpdateApplicationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
