// Code generated by go-swagger; DO NOT EDIT.

package application

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewUploadAppImageParams creates a new UploadAppImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUploadAppImageParams() *UploadAppImageParams {
	return NewUploadAppImageParamsWithTimeout(cr.DefaultTimeout)
}

// NewUploadAppImageParamsWithTimeout creates a new UploadAppImageParams object
// with the ability to set a timeout on a request.
func NewUploadAppImageParamsWithTimeout(timeout time.Duration) *UploadAppImageParams {
	return &UploadAppImageParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewUploadAppImageParamsWithContext creates a new UploadAppImageParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [UploadAppImageParams].
func NewUploadAppImageParamsWithContext(ctx context.Context) *UploadAppImageParams {
	return &UploadAppImageParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewUploadAppImageParamsWithHTTPClient creates a new UploadAppImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewUploadAppImageParamsWithHTTPClient(client *http.Client) *UploadAppImageParams {
	return &UploadAppImageParams{
		HTTPClient: client,
	}
}

/*
UploadAppImageParams contains all the parameters to send to the API endpoint

	for the upload app image operation.

	Typically these are written to a http.Request.
*/
type UploadAppImageParams struct {

	// File.
	//
	// the application image
	File runtime.NamedReadCloser

	// ID.
	//
	// the application id
	//
	// Format: int64
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the upload app image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadAppImageParams) WithDefaults() *UploadAppImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upload app image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadAppImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upload app image params.
func (o *UploadAppImageParams) WithTimeout(timeout time.Duration) *UploadAppImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload app image params.
func (o *UploadAppImageParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the upload app image params.
//
// Deprecated: use the operation call with context to pass the context instead of [UploadAppImageParams].
func (o *UploadAppImageParams) WithContext(ctx context.Context) *UploadAppImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload app image params.
//
// Deprecated: use the operation call with context to pass the context instead of [UploadAppImageParams].
func (o *UploadAppImageParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the upload app image params.
func (o *UploadAppImageParams) WithHTTPClient(client *http.Client) *UploadAppImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload app image params.
func (o *UploadAppImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the upload app image params.
func (o *UploadAppImageParams) WithFile(file runtime.NamedReadCloser) *UploadAppImageParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the upload app image params.
func (o *UploadAppImageParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WithID adds the id to the upload app image params.
func (o *UploadAppImageParams) WithID(id int64) *UploadAppImageParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the upload app image params.
func (o *UploadAppImageParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *UploadAppImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	// form file param file
	if err := r.SetFileParam("file", o.File); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
