// Code generated by go-swagger; DO NOT EDIT.

package message

import (
	"context"
	"net/http"
	"time"

	"github.com/daniel-w-innes/nixos-konnected-exporter/gotify/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateMessageParams creates a new CreateMessageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMessageParams() *CreateMessageParams {
	return NewCreateMessageParamsWithTimeout(cr.DefaultTimeout)
}

// NewCreateMessageParamsWithTimeout creates a new CreateMessageParams object
// with the ability to set a timeout on a request.
func NewCreateMessageParamsWithTimeout(timeout time.Duration) *CreateMessageParams {
	return &CreateMessageParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewCreateMessageParamsWithContext creates a new CreateMessageParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateMessageParams].
func NewCreateMessageParamsWithContext(ctx context.Context) *CreateMessageParams {
	return &CreateMessageParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewCreateMessageParamsWithHTTPClient creates a new CreateMessageParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMessageParamsWithHTTPClient(client *http.Client) *CreateMessageParams {
	return &CreateMessageParams{
		HTTPClient: client,
	}
}

/*
CreateMessageParams contains all the parameters to send to the API endpoint

	for the create message operation.

	Typically these are written to a http.Request.
*/
type CreateMessageParams struct {

	// Body.
	//
	// the message to add
	Body *models.MessageExternal

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the create message params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMessageParams) WithDefaults() *CreateMessageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create message params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMessageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create message params.
func (o *CreateMessageParams) WithTimeout(timeout time.Duration) *CreateMessageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create message params.
func (o *CreateMessageParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the create message params.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateMessageParams].
func (o *CreateMessageParams) WithContext(ctx context.Context) *CreateMessageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create message params.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateMessageParams].
func (o *CreateMessageParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the create message params.
func (o *CreateMessageParams) WithHTTPClient(client *http.Client) *CreateMessageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create message params.
func (o *CreateMessageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create message params.
func (o *CreateMessageParams) WithBody(body *models.MessageExternal) *CreateMessageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create message params.
func (o *CreateMessageParams) SetBody(body *models.MessageExternal) {
	o.Body = body
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *CreateMessageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
