// Code generated by go-swagger; DO NOT EDIT.

package message

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetAppMessagesParams creates a new GetAppMessagesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAppMessagesParams() *GetAppMessagesParams {
	return NewGetAppMessagesParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetAppMessagesParamsWithTimeout creates a new GetAppMessagesParams object
// with the ability to set a timeout on a request.
func NewGetAppMessagesParamsWithTimeout(timeout time.Duration) *GetAppMessagesParams {
	return &GetAppMessagesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetAppMessagesParamsWithContext creates a new GetAppMessagesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAppMessagesParams].
func NewGetAppMessagesParamsWithContext(ctx context.Context) *GetAppMessagesParams {
	return &GetAppMessagesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetAppMessagesParamsWithHTTPClient creates a new GetAppMessagesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAppMessagesParamsWithHTTPClient(client *http.Client) *GetAppMessagesParams {
	return &GetAppMessagesParams{
		HTTPClient: client,
	}
}

/*
GetAppMessagesParams contains all the parameters to send to the API endpoint

	for the get app messages operation.

	Typically these are written to a http.Request.
*/
type GetAppMessagesParams struct {

	// ID.
	//
	// the application id
	//
	// Format: int64
	ID int64

	// Limit.
	//
	// the maximal amount of messages to return
	//
	// Default: 100
	Limit *int64

	// Since.
	//
	// return all messages with an ID less than this value
	//
	// Format: int64
	Since *int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get app messages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAppMessagesParams) WithDefaults() *GetAppMessagesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get app messages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAppMessagesParams) SetDefaults() {
	var (
		limitDefault = int64(100)
	)

	val := GetAppMessagesParams{
		Limit: &limitDefault,
	}

	val.inner.timeout = o.inner.timeout
	val.inner.ctx = o.inner.ctx
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get app messages params.
func (o *GetAppMessagesParams) WithTimeout(timeout time.Duration) *GetAppMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get app messages params.
func (o *GetAppMessagesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get app messages params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAppMessagesParams].
func (o *GetAppMessagesParams) WithContext(ctx context.Context) *GetAppMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get app messages params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAppMessagesParams].
func (o *GetAppMessagesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get app messages params.
func (o *GetAppMessagesParams) WithHTTPClient(client *http.Client) *GetAppMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get app messages params.
func (o *GetAppMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get app messages params.
func (o *GetAppMessagesParams) WithID(id int64) *GetAppMessagesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get app messages params.
func (o *GetAppMessagesParams) SetID(id int64) {
	o.ID = id
}

// WithLimit adds the limit to the get app messages params.
func (o *GetAppMessagesParams) WithLimit(limit *int64) *GetAppMessagesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get app messages params.
func (o *GetAppMessagesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSince adds the since to the get app messages params.
func (o *GetAppMessagesParams) WithSince(since *int64) *GetAppMessagesParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get app messages params.
func (o *GetAppMessagesParams) SetSince(since *int64) {
	o.Since = since
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetAppMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Since != nil {

		// query param since
		var qrSince int64

		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := conv.FormatInteger(qrSince)
		if qSince != "" {

			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
