// Code generated by go-swagger; DO NOT EDIT.

package message

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new message API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new message API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new message API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for message API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// CreateMessage create a message.
	CreateMessage(params *CreateMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMessageOK, error)

	// CreateMessageContext create a message.
	CreateMessageContext(ctx context.Context, params *CreateMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMessageOK, error)

	// DeleteAppMessages delete all messages from a specific application.
	DeleteAppMessages(params *DeleteAppMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAppMessagesOK, error)

	// DeleteAppMessagesContext delete all messages from a specific application.
	DeleteAppMessagesContext(ctx context.Context, params *DeleteAppMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAppMessagesOK, error)

	// DeleteMessage deletes a message with an id.
	DeleteMessage(params *DeleteMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMessageOK, error)

	// DeleteMessageContext deletes a message with an id.
	DeleteMessageContext(ctx context.Context, params *DeleteMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMessageOK, error)

	// DeleteMessages delete all messages.
	DeleteMessages(params *DeleteMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMessagesOK, error)

	// DeleteMessagesContext delete all messages.
	DeleteMessagesContext(ctx context.Context, params *DeleteMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMessagesOK, error)

	// GetAppMessages return all messages from a specific application.
	GetAppMessages(params *GetAppMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAppMessagesOK, error)

	// GetAppMessagesContext return all messages from a specific application.
	GetAppMessagesContext(ctx context.Context, params *GetAppMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAppMessagesOK, error)

	// GetMessages return all messages.
	GetMessages(params *GetMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMessagesOK, error)

	// GetMessagesContext return all messages.
	GetMessagesContext(ctx context.Context, params *GetMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMessagesOK, error)

	// StreamMessages websocket return newly created messages.
	StreamMessages(params *StreamMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StreamMessagesOK, error)

	// StreamMessagesContext websocket return newly created messages.
	StreamMessagesContext(ctx context.Context, params *StreamMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StreamMessagesOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// CreateMessage creates a message.
//
// __NOTE__: This API ONLY accepts an application token as authentication..
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.CreateMessageContext] instead.
func (a *Client) CreateMessage(params *CreateMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMessageOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.CreateMessageContext(ctx, params, authInfo, opts...)
}

// CreateMessageContext creates a message.
//
// __NOTE__: This API ONLY accepts an application token as authentication..
//
// Do not use the deprecated [CreateMessageParams.Context] with this method: it would be ignored.
func (a *Client) CreateMessageContext(ctx context.Context, params *CreateMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMessageOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCreateMessageParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "createMessage",
		Method:             "POST",
		PathPattern:        "/message",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateMessageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CreateMessageOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createMessage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// DeleteAppMessages deletes all messages from a specific application.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteAppMessagesContext] instead.
func (a *Client) DeleteAppMessages(params *DeleteAppMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAppMessagesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteAppMessagesContext(ctx, params, authInfo, opts...)
}

// DeleteAppMessagesContext deletes all messages from a specific application.
//
// Do not use the deprecated [DeleteAppMessagesParams.Context] with this method: it would be ignored.
func (a *Client) DeleteAppMessagesContext(ctx context.Context, params *DeleteAppMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAppMessagesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAppMessagesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteAppMessages",
		Method:             "DELETE",
		PathPattern:        "/application/{id}/message",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteAppMessagesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAppMessagesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteAppMessages: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// DeleteMessage deletes a message with an id.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteMessageContext] instead.
func (a *Client) DeleteMessage(params *DeleteMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMessageOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteMessageContext(ctx, params, authInfo, opts...)
}

// DeleteMessageContext deletes a message with an id.
//
// Do not use the deprecated [DeleteMessageParams.Context] with this method: it would be ignored.
func (a *Client) DeleteMessageContext(ctx context.Context, params *DeleteMessageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMessageOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteMessageParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteMessage",
		Method:             "DELETE",
		PathPattern:        "/message/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteMessageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteMessageOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteMessage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// DeleteMessages deletes all messages.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteMessagesContext] instead.
func (a *Client) DeleteMessages(params *DeleteMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMessagesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteMessagesContext(ctx, params, authInfo, opts...)
}

// DeleteMessagesContext deletes all messages.
//
// Do not use the deprecated [DeleteMessagesParams.Context] with this method: it would be ignored.
func (a *Client) DeleteMessagesContext(ctx context.Context, params *DeleteMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMessagesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteMessagesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "deleteMessages",
		Method:             "DELETE",
		PathPattern:        "/message",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteMessagesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteMessagesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteMessages: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetAppMessages returns all messages from a specific application.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetAppMessagesContext] instead.
func (a *Client) GetAppMessages(params *GetAppMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAppMessagesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetAppMessagesContext(ctx, params, authInfo, opts...)
}

// GetAppMessagesContext returns all messages from a specific application.
//
// Do not use the deprecated [GetAppMessagesParams.Context] with this method: it would be ignored.
func (a *Client) GetAppMessagesContext(ctx context.Context, params *GetAppMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAppMessagesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAppMessagesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getAppMessages",
		Method:             "GET",
		PathPattern:        "/application/{id}/message",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAppMessagesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAppMessagesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getAppMessages: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetMessages returns all messages.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetMessagesContext] instead.
func (a *Client) GetMessages(params *GetMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMessagesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetMessagesContext(ctx, params, authInfo, opts...)
}

// GetMessagesContext returns all messages.
//
// Do not use the deprecated [GetMessagesParams.Context] with this method: it would be ignored.
func (a *Client) GetMessagesContext(ctx context.Context, params *GetMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMessagesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetMessagesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "getMessages",
		Method:             "GET",
		PathPattern:        "/message",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetMessagesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetMessagesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMessages: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// StreamMessages websockets return newly created messages.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.StreamMessagesContext] instead.
func (a *Client) StreamMessages(params *StreamMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StreamMessagesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.StreamMessagesContext(ctx, params, authInfo, opts...)
}

// StreamMessagesContext websockets return newly created messages.
//
// Do not use the deprecated [StreamMessagesParams.Context] with this method: it would be ignored.
func (a *Client) StreamMessagesContext(ctx context.Context, params *StreamMessagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*StreamMessagesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewStreamMessagesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "streamMessages",
		Method:             "GET",
		PathPattern:        "/stream",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &StreamMessagesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*StreamMessagesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for streamMessages: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [MessageParams].
	ctx context.Context
}
