// Code generated by go-swagger; DO NOT EDIT.

package client

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteClientParams creates a new DeleteClientParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteClientParams() *DeleteClientParams {
	return NewDeleteClientParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteClientParamsWithTimeout creates a new DeleteClientParams object
// with the ability to set a timeout on a request.
func NewDeleteClientParamsWithTimeout(timeout time.Duration) *DeleteClientParams {
	return &DeleteClientParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteClientParamsWithContext creates a new DeleteClientParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteClientParams].
func NewDeleteClientParamsWithContext(ctx context.Context) *DeleteClientParams {
	return &DeleteClientParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteClientParamsWithHTTPClient creates a new DeleteClientParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteClientParamsWithHTTPClient(client *http.Client) *DeleteClientParams {
	return &DeleteClientParams{
		HTTPClient: client,
	}
}

/*
DeleteClientParams contains all the parameters to send to the API endpoint

	for the delete client operation.

	Typically these are written to a http.Request.
*/
type DeleteClientParams struct {

	// ID.
	//
	// the client id
	//
	// Format: int64
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete client params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteClientParams) WithDefaults() *DeleteClientParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete client params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteClientParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete client params.
func (o *DeleteClientParams) WithTimeout(timeout time.Duration) *DeleteClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete client params.
func (o *DeleteClientParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete client params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteClientParams].
func (o *DeleteClientParams) WithContext(ctx context.Context) *DeleteClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete client params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteClientParams].
func (o *DeleteClientParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete client params.
func (o *DeleteClientParams) WithHTTPClient(client *http.Client) *DeleteClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete client params.
func (o *DeleteClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete client params.
func (o *DeleteClientParams) WithID(id int64) *DeleteClientParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete client params.
func (o *DeleteClientParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
