// Code generated by go-swagger; DO NOT EDIT.

package client

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClientsParams creates a new GetClientsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClientsParams() *GetClientsParams {
	return NewGetClientsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetClientsParamsWithTimeout creates a new GetClientsParams object
// with the ability to set a timeout on a request.
func NewGetClientsParamsWithTimeout(timeout time.Duration) *GetClientsParams {
	return &GetClientsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetClientsParamsWithContext creates a new GetClientsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetClientsParams].
func NewGetClientsParamsWithContext(ctx context.Context) *GetClientsParams {
	return &GetClientsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetClientsParamsWithHTTPClient creates a new GetClientsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClientsParamsWithHTTPClient(client *http.Client) *GetClientsParams {
	return &GetClientsParams{
		HTTPClient: client,
	}
}

/*
GetClientsParams contains all the parameters to send to the API endpoint

	for the get clients operation.

	Typically these are written to a http.Request.
*/
type GetClientsParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get clients params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClientsParams) WithDefaults() *GetClientsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get clients params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClientsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get clients params.
func (o *GetClientsParams) WithTimeout(timeout time.Duration) *GetClientsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get clients params.
func (o *GetClientsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get clients params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetClientsParams].
func (o *GetClientsParams) WithContext(ctx context.Context) *GetClientsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get clients params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetClientsParams].
func (o *GetClientsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get clients params.
func (o *GetClientsParams) WithHTTPClient(client *http.Client) *GetClientsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get clients params.
func (o *GetClientsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetClientsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
