// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Application Application Model
//
// The Application holds information about an app which can send notifications.
//
// swagger:model Application
type Application struct {

	// The default priority of messages sent by this application. Defaults to 0.
	// Example: 4
	DefaultPriority int64 `json:"defaultPriority,omitempty"`

	// The description of the application.
	// Example: Backup server for the interwebs
	// Required: true
	Description *string `json:"description"`

	// The application id.
	// Example: 5
	// Required: true
	// Read Only: true
	ID int64 `json:"id"`

	// The image of the application.
	// Example: image/image.jpeg
	// Required: true
	// Read Only: true
	Image string `json:"image"`

	// Whether the application is an internal application. Internal applications should not be deleted.
	// Example: false
	// Required: true
	// Read Only: true
	Internal bool `json:"internal"`

	// The last time the application token was used.
	// Example: 2019-01-01T00:00:00Z
	// Read Only: true
	// Format: date-time
	LastUsed strfmt.DateTime `json:"lastUsed,omitempty"`

	// The application name. This is how the application should be displayed to the user.
	// Example: Backup Server
	// Required: true
	Name *string `json:"name"`

	// The sort key of this application. Uses fractional indexing.
	// Example: a1
	// Required: true
	SortKey *string `json:"sortKey"`

	// The application token. Can be used as `appToken`. See Authentication.
	// Example: AWH0wZ5r0Mbac.r
	// Required: true
	// Read Only: true
	Token string `json:"token"`
}

// Validate validates this application
func (m *Application) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInternal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastUsed(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSortKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Application) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateImage(formats strfmt.Registry) error {

	if err := validate.RequiredString("image", "body", m.Image); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateInternal(formats strfmt.Registry) error {

	if err := validate.Required("internal", "body", m.Internal); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateLastUsed(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LastUsed) { // not required
		return nil
	}

	if err := validate.FormatOf("lastUsed", "body", "date-time", m.LastUsed.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateSortKey(formats strfmt.Registry) error {

	if err := validate.Required("sortKey", "body", m.SortKey); err != nil {
		return err
	}

	return nil
}

func (m *Application) validateToken(formats strfmt.Registry) error {

	if err := validate.RequiredString("token", "body", m.Token); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this application based on the context it is used
func (m *Application) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInternal(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastUsed(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateToken(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Application) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Application) contextValidateImage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "image", "body", m.Image); err != nil {
		return err
	}

	return nil
}

func (m *Application) contextValidateInternal(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "internal", "body", m.Internal); err != nil {
		return err
	}

	return nil
}

func (m *Application) contextValidateLastUsed(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "lastUsed", "body", m.LastUsed); err != nil {
		return err
	}

	return nil
}

func (m *Application) contextValidateToken(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "token", "body", m.Token); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Application) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Application) UnmarshalBinary(b []byte) error {
	var res Application
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
