// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// ApplicationParams Application Params Model
//
// Params allowed to create or update Applications.
//
// swagger:model ApplicationParams
type ApplicationParams struct {

	// The default priority of messages sent by this application. Defaults to 0.
	// Example: 5
	DefaultPriority int64 `json:"defaultPriority,omitempty"`

	// The description of the application.
	// Example: Backup server for the interwebs
	Description string `json:"description,omitempty"`

	// The application name. This is how the application should be displayed to the user.
	// Example: Backup Server
	// Required: true
	Name *string `json:"name"`

	// The sortKey for the application. Uses fractional indexing.
	// Example: a1
	SortKey string `json:"sortKey,omitempty"`
}

// Validate validates this application params
func (m *ApplicationParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApplicationParams) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this application params based on context it is used
func (m *ApplicationParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationParams) UnmarshalBinary(b []byte) error {
	var res ApplicationParams
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
