// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// CreateUserExternal CreateUserExternal Model
//
// Used for user creation.
//
// swagger:model CreateUserExternal
type CreateUserExternal struct {

	// If the user is an administrator.
	// Example: true
	// Required: true
	Admin *bool `json:"admin"`

	// The user name. For login.
	// Example: unicorn
	// Required: true
	Name *string `json:"name"`

	// The user password. For login.
	// Example: nrocinu
	// Required: true
	Pass *string `json:"pass"`
}

// Validate validates this create user external
func (m *CreateUserExternal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdmin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePass(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateUserExternal) validateAdmin(formats strfmt.Registry) error {

	if err := validate.Required("admin", "body", m.Admin); err != nil {
		return err
	}

	return nil
}

func (m *CreateUserExternal) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *CreateUserExternal) validatePass(formats strfmt.Registry) error {

	if err := validate.Required("pass", "body", m.Pass); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create user external based on context it is used
func (m *CreateUserExternal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateUserExternal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateUserExternal) UnmarshalBinary(b []byte) error {
	var res CreateUserExternal
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
