// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// MessageExternal MessageExternal Model
//
// The MessageExternal holds information about a message which was sent by an Application.
//
// swagger:model MessageExternal
type MessageExternal struct {

	// The application id that send this message.
	// Example: 5
	// Required: true
	// Read Only: true
	ApplicationID int64 `json:"appid"`

	// The date the message was created.
	// Example: 2018-02-27T19:36:10.5045044+01:00
	// Required: true
	// Read Only: true
	// Format: date-time
	Date strfmt.DateTime `json:"date"`

	// The extra data sent along the message.
	//
	// The extra fields are stored in a key-value scheme. Only accepted in CreateMessage requests with application/json content-type.
	//
	// The keys should be in the following format: &lt;top-namespace&gt;::[&lt;sub-namespace&gt;::]&lt;action&gt;
	//
	// These namespaces are reserved and might be used in the official clients: gotify android ios web server client. Do not use them for other purposes.
	// Example: {"home::appliances::lighting::on":{"brightness":15},"home::appliances::thermostat::change_temperature":{"temperature":23}}
	Extras map[string]any `json:"extras,omitempty"`

	// The message id.
	// Example: 25
	// Required: true
	// Read Only: true
	ID int64 `json:"id"`

	// The message. Markdown (excluding html) is allowed.
	// Example: **Backup** was successfully finished.
	// Required: true
	Message *string `json:"message"`

	// The priority of the message. If unset, then the default priority of the
	// application will be used.
	// Example: 2
	Priority int64 `json:"priority,omitempty"`

	// The title of the message.
	// Example: Backup
	Title string `json:"title,omitempty"`
}

// Validate validates this message external
func (m *MessageExternal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplicationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MessageExternal) validateApplicationID(formats strfmt.Registry) error {

	if err := validate.Required("appid", "body", m.ApplicationID); err != nil {
		return err
	}

	return nil
}

func (m *MessageExternal) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("date", "body", m.Date); err != nil {
		return err
	}

	if err := validate.FormatOf("date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *MessageExternal) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *MessageExternal) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this message external based on the context it is used
func (m *MessageExternal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateApplicationID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MessageExternal) contextValidateApplicationID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "appid", "body", m.ApplicationID); err != nil {
		return err
	}

	return nil
}

func (m *MessageExternal) contextValidateDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "date", "body", m.Date); err != nil {
		return err
	}

	return nil
}

func (m *MessageExternal) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MessageExternal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MessageExternal) UnmarshalBinary(b []byte) error {
	var res MessageExternal
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
