// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// Paging Paging Model
//
// The Paging holds information about the limit and making requests to the next page.
//
// swagger:model Paging
type Paging struct {

	// The limit of the messages for the current request.
	// Example: 123
	// Required: true
	// Read Only: true
	// Maximum: 200
	// Minimum: 1
	Limit int64 `json:"limit"`

	// The request url for the next page. Empty/Null when no next page is available.
	// Example: http://example.com/message?limit=50\u0026since=123456
	// Read Only: true
	Next string `json:"next,omitempty"`

	// The ID of the last message returned in the current request. Use this as alternative to the next link.
	// Example: 5
	// Required: true
	// Read Only: true
	// Minimum: 0
	Since int64 `json:"since"`

	// The amount of messages that got returned in the current request.
	// Example: 5
	// Required: true
	// Read Only: true
	Size int64 `json:"size"`
}

// Validate validates this paging
func (m *Paging) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSince(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Paging) validateLimit(formats strfmt.Registry) error {

	if err := validate.Required("limit", "body", m.Limit); err != nil {
		return err
	}

	if err := validate.MinimumInt("limit", "body", m.Limit, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("limit", "body", m.Limit, 200, false); err != nil {
		return err
	}

	return nil
}

func (m *Paging) validateSince(formats strfmt.Registry) error {

	if err := validate.Required("since", "body", m.Since); err != nil {
		return err
	}

	if err := validate.MinimumInt("since", "body", m.Since, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *Paging) validateSize(formats strfmt.Registry) error {

	if err := validate.Required("size", "body", m.Size); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this paging based on the context it is used
func (m *Paging) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLimit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNext(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSince(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSize(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Paging) contextValidateLimit(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "limit", "body", m.Limit); err != nil {
		return err
	}

	return nil
}

func (m *Paging) contextValidateNext(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "next", "body", m.Next); err != nil {
		return err
	}

	return nil
}

func (m *Paging) contextValidateSince(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "since", "body", m.Since); err != nil {
		return err
	}

	return nil
}

func (m *Paging) contextValidateSize(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "size", "body", m.Size); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Paging) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Paging) UnmarshalBinary(b []byte) error {
	var res Paging
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
