// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// PluginConfExternal PluginConfExternal Model
//
// Holds information about a plugin instance for one user.
//
// swagger:model PluginConfExternal
type PluginConfExternal struct {

	// The author of the plugin.
	// Example: jmattheis
	// Read Only: true
	Author string `json:"author,omitempty"`

	// Capabilities the plugin provides
	// Example: ["webhook","display"]
	// Required: true
	Capabilities []string `json:"capabilities"`

	// Whether the plugin instance is enabled.
	// Example: true
	// Required: true
	Enabled *bool `json:"enabled"`

	// The plugin id.
	// Example: 25
	// Required: true
	// Read Only: true
	ID int64 `json:"id"`

	// The license of the plugin.
	// Example: MIT
	// Read Only: true
	License string `json:"license,omitempty"`

	// The module path of the plugin.
	// Example: github.com/gotify/server/plugin/example/echo
	// Required: true
	// Read Only: true
	ModulePath string `json:"modulePath"`

	// The plugin name.
	// Example: RSS poller
	// Required: true
	// Read Only: true
	Name string `json:"name"`

	// The user name. For login.
	// Example: P1234
	// Required: true
	Token *string `json:"token"`

	// The website of the plugin.
	// Example: gotify.net
	// Read Only: true
	Website string `json:"website,omitempty"`
}

// Validate validates this plugin conf external
func (m *PluginConfExternal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCapabilities(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModulePath(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PluginConfExternal) validateCapabilities(formats strfmt.Registry) error {

	if err := validate.Required("capabilities", "body", m.Capabilities); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("enabled", "body", m.Enabled); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) validateModulePath(formats strfmt.Registry) error {

	if err := validate.RequiredString("modulePath", "body", m.ModulePath); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) validateToken(formats strfmt.Registry) error {

	if err := validate.Required("token", "body", m.Token); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this plugin conf external based on the context it is used
func (m *PluginConfExternal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAuthor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLicense(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateModulePath(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWebsite(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PluginConfExternal) contextValidateAuthor(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "author", "body", m.Author); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) contextValidateLicense(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "license", "body", m.License); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) contextValidateModulePath(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "modulePath", "body", m.ModulePath); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) contextValidateName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *PluginConfExternal) contextValidateWebsite(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "website", "body", m.Website); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PluginConfExternal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PluginConfExternal) UnmarshalBinary(b []byte) error {
	var res PluginConfExternal
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
