// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// UpdateUserExternal UpdateUserExternal Model
//
// Used for updating a user.
//
// swagger:model UpdateUserExternal
type UpdateUserExternal struct {

	// If the user is an administrator.
	// Example: true
	// Required: true
	Admin *bool `json:"admin"`

	// The user name. For login.
	// Example: unicorn
	// Required: true
	Name *string `json:"name"`

	// The user password. For login. Empty for using old password
	// Example: nrocinu
	Pass string `json:"pass,omitempty"`
}

// Validate validates this update user external
func (m *UpdateUserExternal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdmin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateUserExternal) validateAdmin(formats strfmt.Registry) error {

	if err := validate.Required("admin", "body", m.Admin); err != nil {
		return err
	}

	return nil
}

func (m *UpdateUserExternal) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update user external based on context it is used
func (m *UpdateUserExternal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateUserExternal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateUserExternal) UnmarshalBinary(b []byte) error {
	var res UpdateUserExternal
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
