// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// UserExternalPass UserExternalPass Model
//
// The Password for updating the user.
//
// swagger:model UserExternalPass
type UserExternalPass struct {

	// The user password. For login.
	// Example: nrocinu
	// Required: true
	Pass *string `json:"pass"`
}

// Validate validates this user external pass
func (m *UserExternalPass) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePass(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserExternalPass) validatePass(formats strfmt.Registry) error {

	if err := validate.Required("pass", "body", m.Pass); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user external pass based on context it is used
func (m *UserExternalPass) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserExternalPass) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserExternalPass) UnmarshalBinary(b []byte) error {
	var res UserExternalPass
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
