name: NixOS check and build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        hostname:
          - cucamelon

    steps:
      - uses: actions/checkout@v2.3.2
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: gvolpe-nixos
      - uses: wimpysworld/nothing-but-nix@main
      - name: "Build ${{ matrix.config_name }} NixOS config ❄️"
        run: nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel -L
