name: NixOS check and build
on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    outputs:
      garnix: ${{ steps.garnix.outputs.status }}
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Garnix check status
        id: garnix
        uses: ./.github/actions/garnix-check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: checks
    if: needs.checks.outputs.garnix == 'failure'
    strategy:
      fail-fast: true
      matrix:
        hostname:
          - cucamelon
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: gvolpe-nixos
      - name: "Build ${{ matrix.config_name }} NixOS config ❄️"
        run: nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel -L
