# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" "dm-mirror" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5113dc4a-5ed5-4688-a991-539bdd9e5ba5";
    fsType = "ext4";
  };
  boot.initrd.luks.devices = {
    lvm1.device = "/dev/disk/by-uuid/6fe0ec0f-041e-46e8-bf05-9ddc4a8087bb";
    lvm2.device = "/dev/disk/by-uuid/a0422975-ecec-4d24-a693-d8bee5fac314";
    "luks-cda04856-752e-451d-a132-04620721de59".device =
      "/dev/disk/by-uuid/cda04856-752e-451d-a132-04620721de59";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/772D-0297";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  #fileSystems."/home/daniel" = {
  #  device = "/dev/disk/by-uuid/9d67d240-730b-4763-b43e-3f65f4cdf2cd";
  #  fsType = "btrfs";
  #};

  fileSystems."/home/daniel/games" = {
    device = "/dev/disk/by-uuid/92aa571b-c395-4e3b-8370-4a34cde82c16";
    fsType = "btrfs";
  };

  fileSystems."/home/daniel/Documents" = {
    device = "/dev/disk/by-uuid/98732021-a852-4977-9183-e444c6312c18";
    fsType = "btrfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/959b6e58-75ef-4583-816a-cfecf5ebd1d7"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
